apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-con-server
  labels:
    app: go-con-server
spec:
  selector:
    matchLabels:
      app: go-con-server
  replicas: 1
  template:
    metadata:
      labels:
        app: go-con-server
    spec:
      containers:
        - name: master
          image: go-con-server
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080