apiVersion: v1
kind: Service
metadata:
  name: go-con-server
  labels:
    app: go-con-server
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30020
      name: client
  selector:
    app: go-con-server